version: 2
jobs:
  build:
    machine: true
    parallelism: 1
    environment:
      KNIFE_ENV: test
    working_directory: ~/chef-repo
    steps:
      - checkout
      - run:
          name: Converge all kitchen cookbooks
          command: |
            for test_instance in $(.circleci/bin/kitchen-tests-for-build | circleci tests split);
            do
              .circleci/bin/run-in-cookbook "$(dirname $test_instance)" bundle exec kitchen converge "$(basename $test_instance)"
            done
      - run:
          name: Verify all kitchen cookbooks
          command: |
            for test_instance in $(.circleci/bin/kitchen-tests-for-build | circleci tests split);
            do
              .circleci/bin/run-in-cookbook "$(dirname $test_instance)" bundle exec kitchen verify "$(basename $test_instance)"
            done
