version: 2
jobs:
  build:
    docker:
      - image: circleci/classic:latest
    steps:
      - run:
          name:  Install Chef
          command: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -c current -P chefdk

      - run:
          name: Install gems inside Chef Omnibus
          command: chef exec bundle install

      - run:
          name: Kitchen verify
          command: chef exec bundle exec kitchen verify
