version: 2
jobs:
  build:
    docker:
      - image: kinesis/ruby@sha256:b54fc2798df0a14c139b58d5f95167d2a032c4f9a11c1b787535179d23cd7326
    steps:
      - run:
          name:  Install Chef
          command: curl -L https://www.chef.io/chef/install.sh | bash -s -- -v 1.3.43 -P chefdk

      - run:
          name: Install gems inside Chef Omnibus
          command: chef exec bundle install

      - run:
          name: Kitchen verify
          command: chef exec bundle exec kitchen verify
