version: 2
jobs:
  build:
    docker:
      - image: chef/chefdk
    steps:
      - run:
          name: Install gems inside Chef Omnibus
          command: chef exec bundle install

      - run:
          name: Kitchen verify
          command: chef exec bundle exec kitchen verify
