version: 2
jobs:
  build:
    services:
      - docker
    steps:
      - run:
          name:  Install Chef
          command: curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -v 1.3.43 -P chefdk

      - run:
          name: Install gems inside Chef Omnibus
          command: chef exec bundle install

      - run:
          name: Kitchen verify
          command: chef exec bundle exec kitchen verify
